### ISSUE TITLE
Plot resize doesn't work for CSS grid layout

### ISSUE THREAD

**Issue by swiperii** [plotly/react-plotly.js#102]
The Plot component doesn't resize properly when using CSS grid for page layout. 
It will grow, but it never shrinks.

Example:
https://codepen.io/swiperii/pen/qMgdwO?editors=0010

**Comment by nicolaskruchten** [comment]
@antoinerg can you take a look at this one please?

**Comment by antoinerg** [comment]
This one should be fixed when plotly.js v1.42.0 is released! 🎉

**Comment by antoinerg** [comment]
Due to a recent commit https://github.com/plotly/plotly.js/pull/3090/commits/af4a2cefe10de4eb855f31c9503cb87e68458a90, `useResizeHandler` will have to set plotly.js config option `responsive: true` in order to fix the current issue. By doing so, plotly.js will handle responsiveness. Hopefully this transition goes smoothly.

@nicolaskruchten We can talk about it when v1.42.0 is released!

**Comment by findoslice** [comment]
I'm still having the same issue, using `react-plotly.js@2.3.0` and `pltly.js@1.48.3`

**Comment by antoinerg** [comment]
@findoslice If you specify `responsive: true` in the config option it should work properly: https://codepen.io/antoinerg/pen/wLOygM?editors=0010

**Comment by antoinerg** [comment]
@findoslice Can you confirm the above fixes your issue?

**Comment by findoslice** [comment]
@antoinerg Unfortunately I no longer work for the company where this issue came up, however from memory it didn't at the time

**Comment by MasonPinZ** [comment]
@antoinerg I encountered the same issue and I also confirmed that your suggestion fixed my issue. Thanks a lot!

> @findoslice If you specify `responsive: true` in the config option it should work properly: https://codepen.io/antoinerg/pen/wLOygM?editors=0010

**Comment by DonaldHokanson** [comment]
@antoinerg I also had the same issue using CSS Grid and I can confirm your suggestion works.  I'm using React in an Electron app and my code looks like this:

`        <Plot
          useResizeHandler
          style={{ height: '100%', width: '100%' }}
          data={[
            {
              x: signalTime,
              y: signalData,
              mode: 'lines',
              marker: { color: 'red' },
            },
          ]}
          layout={{
            autosize: true,
            margin: { t: 50, l: 45, r: 45, b: 40 },
            title: 'A Fancy Plot',
            xaxis: { title: 'Time in seconds' },
            yaxis: { title: 'X Track Error' },
          }}
          config={{ scrollZoom: true, responsive: true }}
        />`
